### ISSUE TITLE
El Capitan issue: Linked to precompiled Ogg.Framework for Mac app.

### ISSUE THREAD

**Issue by blnked** [iosdevzone/IDZPrecompiledOgg#6]
Any help to solve issue: ..../IDZPrecompiledOgg/Ogg.framework/Ogg(framing.o), building for OSX, but linking in object file built for iOS, for architecture x86_64

Thanks

**Comment by iosdevzone** [comment]
This project is for iOS, not OS X.

**Comment by blnked** [comment]
thanks for quick reply. I used yours projects (like IDZPrecompiledFLAC and IDZPrecompiledOgg) for IOS app and have been hope to use for Mac app.

**Comment by iosdevzone** [comment]
I never thought of making the scripts work for OS X as you can build the source directly with a few commands or you can use `homebrew` (See: http://brew.sh) to install binaries.  

In either of these cases, using the library is not quite as easy since it is not packaged as a framework, so you may need to set you library and header search paths appropriately.

Maybe I should try to tweak the scripts... Won't be something I'll get to in the next few days though. Sorry!

**Comment by blnked** [comment]
You're right (for OS X more easier) thank you for your thoughts and direction
